### ISSUE TITLE
Lay of the Land Presentation

### ISSUE THREAD

**Issue by iomartin** [tsajed/kokoriko#10]
These are the questions that need to be addressed in the presentation.
- What PERFORMANCE task is being addressed? 
- What is LEARNING task?  (Input/Output/ ...)
- Why is this performance/learning problem important?
- Why isn't this task trivial? 
- What have (other) people done, to solve this problem?
- How does this TEAM plan to address this task?

**Comment by shrimanti** [comment]
Hey, Yesterday I was actually looking for literature survey and other previously published approaches to solve our problem, I will send some papers regarding this, once I come back.

**Comment by shrimanti** [comment]
But I thing I wanted to confirm, are we not supposed to present some preliminary results ? 
I mean we should try to complete the pre-processing of data and create our labeled training sets and spectrogram computation from the signals. 
After that we have to construct and train the models (RNN and CNN) feeding our training data.

**Comment by shrimanti** [comment]
I will try to construct the architecture for RNN using LSTM.

**Comment by iomartin** [comment]
@shrimanti I don't think we have to present results, at least that's what I understood from last class. Sure, if we do have some results, we should by all means present them, but the goal of this presentation is to take a step back and reflect about what, why and how we want to do.
