### ISSUE TITLE
Task: Artificially noisy data

### ISSUE THREAD

**Issue by efferifick** [tsajed/kokoriko#11]
We have 160 clean audio files where OSFL is singing and many many more clean for different birds.
All of these have spectrograms.

We need a way of combining these two to get more noisy data.

**Comment by iomartin** [comment]
I'm generating the data as I type.
I'm randomly combining audio files 2 by 2.
This will create 1837 data points.

**Comment by efferifick** [comment]
Are you combining the audio files or the spectrograms?

**Comment by iomartin** [comment]
Audio files. Then we can pass them through your spectogram generator.

**Comment by efferifick** [comment]
This is great Martin! Are you keeping track of which two audio files you are combining?

**Comment by efferifick** [comment]
Also, if you download and install git-lfs you should be able to upload this data to a repository.

**Comment by iomartin** [comment]
Yes, I record which files are being combined. Also, because they have different durations, the length of the output file will have the length of the shortest (this is also recorded).

I'll have a look at git-lfs, thanks for the hint ;)

**Comment by efferifick** [comment]
AWESOME! Super useful! Thanks!

**Comment by iomartin** [comment]
I have added all files to a repository.
