### ISSUE TITLE
Data Organization

### ISSUE THREAD

**Issue by iomartin** [tsajed/kokoriko#8]
I was thinking how we should organize all our recordings.

My proposal is that we have use an XML file for that, with the following structure:

For a single data point, we will three fields: file name and whether it contains a bird and/or noise. Also, each data point can be the composition of multiple other files, so we also a list of all files that were used to make that data point.

Below is a schema of what I have in mind. What do you think?

``` xml
<birds>
  <datapoint>
    <filename>String</filename>
    <hasBird>Boolean</hasBird>
    <hasNoise>Boolean</hasNoise>
    <!-- A recording may be the composition of others. This list specifies which files were combined into this one. It can be an empty list (in the case for the original recordings) -->
    <compositionOf>
        <!-- First file -->
        <file>
          <!-- For each file, we list the file name and to which portion of the recording it corresponds to -->
          <filename>String</filename>
          <startTime>Float</startTime>
          <endTime>Float</endTime>
        </file>
        <!-- Second file, etc -->
        <file>
          <filename>String</filename>
          <startTime>Float</startTime>
          <endTime>Float</endTime>
        </file>
    </compositionOf>
  </datapoint>
  <datapoint>
  ...
  </datapoint>
</birds>
```

**Comment by shrimanti** [comment]
So, "each data point can be the composition of multiple other files" means the overlapping between 2 different species, right?

**Comment by shrimanti** [comment]
I think for me the structure looks fine.

**Comment by shrimanti** [comment]
But, how are we going to choose the combination of 2 different bird species?

**Comment by efferifick** [comment]
@iomartin  Looks fine!
@shrimanti We could do it randomly... or maximize the number of overlaps... or something of the sort.

**Comment by shrimanti** [comment]
Okay.

**Comment by iomartin** [comment]
We can use [this python module](https://docs.python.org/3/library/xml.etree.elementtree.html) to read/write XML files.

**Comment by iomartin** [comment]
I have pushed an example of parsing an XML on a new branch. df027afe9f2268128ff65787a9868430e80ef5ab

I have also slightly changed the XML schema for the below. The main difference is that `<compositionOf>` is now a list of other `<datapoint>`s. Naturally, this is just a suggestion and we can change it as needed.

``` xml
<birds>
  <datapoint>
    <filename>input1</filename>
    <isBird>True</isBird>
    <isNoise>False</isNoise>
    <compositionOf>
        <datapoint>
          <filename>file1</filename>
          <startTime>1.0</startTime>
          <endTime>3.0</endTime>
        </datapoint>
        <datapoint>
          <filename>file2</filename>
          <startTime>2.0</startTime>
          <endTime>2.5</endTime>
        </datapoint>
    </compositionOf>
  </datapoint>
  <datapoint>
    <filename>input2</filename>
    <isBird>False</isBird>
    <isNoise>False</isNoise>
    <!-- This may be an empty list (useful for the original files, which are not the composition of any other files) -->
    <compositionOf>
    </compositionOf>
  </datapoint>
</birds>
```
